snapshot of project "vile", label v9_7u7

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.272 .
+# From configure.in Revision: 1.274 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.20081225.
 #
@@ -21276,7 +21276,8 @@ echo "$as_me: WARNING: You should get a working version of flex, for instance:
 fi
 
 if test "$TARGET" = xvile; then
-	echo "$as_me:21279: checking for directory to install resource files" >&5
+
+	echo "$as_me:21280: checking for directory to install resource files" >&5
 echo $ECHO_N "checking for directory to install resource files... $ECHO_C" >&6
 
 # Check whether --with-app-defaults or --without-app-defaults was given.
@@ -21284,8 +21285,8 @@ if test "${with_app_defaults+set}" = set; then
   withval="$with_app_defaults"
 
 else
-  withval="${appsdir-'\$(exec_prefix)/lib/X11/app-defaults'}"
-fi; if test -n "'\$(exec_prefix)/lib/X11/app-defaults'" ; then
+  withval="${appsdir-'\${exec_prefix}/lib/X11/app-defaults'}"
+fi; if test -n "'\${exec_prefix}/lib/X11/app-defaults'" ; then
 
 if test "x$prefix" != xNONE; then
   cf_path_syntax="$prefix"
@@ -21312,7 +21313,7 @@ case ".$withval" in #(vi
   withval=`echo $withval | sed -e s%NONE%$cf_path_syntax%`
   ;;
 *)
-  { { echo "$as_me:21315: error: expected a pathname, not \"$withval\"" >&5
+  { { echo "$as_me:21316: error: expected a pathname, not \"$withval\"" >&5
 echo "$as_me: error: expected a pathname, not \"$withval\"" >&2;}
    { (exit 1); exit 1; }; }
   ;;
@@ -21321,55 +21322,7 @@ esac
 fi
 appsdir="$withval"
 
-	echo "$as_me:21324: result: $appsdir" >&5
-echo "${ECHO_T}$appsdir" >&6
-
-	echo "$as_me:21327: checking for directory to install resource files" >&5
-echo $ECHO_N "checking for directory to install resource files... $ECHO_C" >&6
-
-# Check whether --with-app-defaults or --without-app-defaults was given.
-if test "${with_app_defaults+set}" = set; then
-  withval="$with_app_defaults"
-
-else
-  withval="${appsdir-'\$(exec_prefix)/lib/X11/app-defaults'}"
-fi; if test -n "'\$(exec_prefix)/lib/X11/app-defaults'" ; then
-
-if test "x$prefix" != xNONE; then
-  cf_path_syntax="$prefix"
-else
-  cf_path_syntax="$ac_default_prefix"
-fi
-
-case ".$withval" in #(vi
-.\$\(*\)*|.\'*\'*) #(vi
-  ;;
-..|./*|.\\*) #(vi
-  ;;
-.[a-zA-Z]:[\\/]*) #(vi OS/2 EMX
-  ;;
-.\${*prefix}*) #(vi
-  eval withval="$withval"
-  case ".$withval" in #(vi
-  .NONE/*)
-    withval=`echo $withval | sed -e s%NONE%$cf_path_syntax%`
-    ;;
-  esac
-  ;; #(vi
-.no|.NONE/*)
-  withval=`echo $withval | sed -e s%NONE%$cf_path_syntax%`
-  ;;
-*)
-  { { echo "$as_me:21363: error: expected a pathname, not \"$withval\"" >&5
-echo "$as_me: error: expected a pathname, not \"$withval\"" >&2;}
-   { (exit 1); exit 1; }; }
-  ;;
-esac
-
-fi
-appsdir="$withval"
-
-	echo "$as_me:21372: result: $appsdir" >&5
+	echo "$as_me:21325: result: $appsdir" >&5
 echo "${ECHO_T}$appsdir" >&6
 
 	no_appsdir=
@@ -21379,7 +21332,7 @@ echo "${ECHO_T}$appsdir" >&6
 		EXTRA_INSTALL_DIRS="$EXTRA_INSTALL_DIRS \$(APPSDIR)"
 	fi
 
-	echo "$as_me:21382: checking for directory to install icons" >&5
+	echo "$as_me:21335: checking for directory to install icons" >&5
 echo $ECHO_N "checking for directory to install icons... $ECHO_C" >&6
 
 # Check whether --with-icondir or --without-icondir was given.
@@ -21387,8 +21340,8 @@ if test "${with_icondir+set}" = set; then
   withval="$with_icondir"
 
 else
-  withval="${icondir-'\$(exec_prefix)/share/pixmaps'}"
-fi; if test -n "'\$(exec_prefix)/share/pixmaps'" ; then
+  withval="${icondir-'\${exec_prefix}/share/pixmaps'}"
+fi; if test -n "'\${exec_prefix}/share/pixmaps'" ; then
 
 if test "x$prefix" != xNONE; then
   cf_path_syntax="$prefix"
@@ -21415,7 +21368,7 @@ case ".$withval" in #(vi
   withval=`echo $withval | sed -e s%NONE%$cf_path_syntax%`
   ;;
 *)
-  { { echo "$as_me:21418: error: expected a pathname, not \"$withval\"" >&5
+  { { echo "$as_me:21371: error: expected a pathname, not \"$withval\"" >&5
 echo "$as_me: error: expected a pathname, not \"$withval\"" >&2;}
    { (exit 1); exit 1; }; }
   ;;
@@ -21424,7 +21377,7 @@ esac
 fi
 icondir="$withval"
 
-	echo "$as_me:21427: result: $icondir" >&5
+	echo "$as_me:21380: result: $icondir" >&5
 echo "${ECHO_T}$icondir" >&6
 
 	no_icondir=
@@ -21435,7 +21388,7 @@ echo "${ECHO_T}$icondir" >&6
 	fi
 
 	# Comment-out the install-desktop rule if the desktop-utils are not found.
-	echo "$as_me:21438: checking if you want to install desktop files" >&5
+	echo "$as_me:21391: checking if you want to install desktop files" >&5
 echo $ECHO_N "checking if you want to install desktop files... $ECHO_C" >&6
 
 # Check whether --enable-desktop or --disable-desktop was given.
@@ -21452,14 +21405,14 @@ else
   enable_desktop=$enableval
 
 fi;
-	echo "$as_me:21455: result: $enable_desktop" >&5
+	echo "$as_me:21408: result: $enable_desktop" >&5
 echo "${ECHO_T}$enable_desktop" >&6
 
 	desktop_utils=
 	if test "$enable_desktop" = yes ; then
 	# Extract the first word of "desktop-file-install", so it can be a program name with args.
 set dummy desktop-file-install; ac_word=$2
-echo "$as_me:21462: checking for $ac_word" >&5
+echo "$as_me:21415: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
 if test "${ac_cv_prog_desktop_utils+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
@@ -21474,7 +21427,7 @@ for ac_dir in $ac_dummy; do
   test -z "$ac_dir" && ac_dir=.
   $as_executable_p "$ac_dir/$ac_word" || continue
 ac_cv_prog_desktop_utils="yes"
-echo "$as_me:21477: found $ac_dir/$ac_word" >&5
+echo "$as_me:21430: found $ac_dir/$ac_word" >&5
 break
 done
 
@@ -21483,10 +21436,10 @@ fi
 fi
 desktop_utils=$ac_cv_prog_desktop_utils
 if test -n "$desktop_utils"; then
-  echo "$as_me:21486: result: $desktop_utils" >&5
+  echo "$as_me:21439: result: $desktop_utils" >&5
 echo "${ECHO_T}$desktop_utils" >&6
 else
-  echo "$as_me:21489: result: no" >&5
+  echo "$as_me:21442: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
@@ -21581,7 +21534,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:21584: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:21537: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -21757,7 +21710,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:21760: error: ambiguous option: $1
+    { { echo "$as_me:21713: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -21776,7 +21729,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:21779: error: unrecognized option: $1
+  -*) { { echo "$as_me:21732: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -21835,7 +21788,7 @@ do
   "filters/makefile.tmp" ) CONFIG_FILES="$CONFIG_FILES filters/makefile.tmp:filters/makefile.2nd" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config_h.in" ;;
-  *) { { echo "$as_me:21838: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:21791: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -22112,7 +22065,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:22115: creating $ac_file" >&5
+    { echo "$as_me:22068: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -22130,7 +22083,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22133: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22086: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22143,7 +22096,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22146: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22099: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22209,7 +22162,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:22212: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:22165: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -22220,7 +22173,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:22223: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:22176: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -22233,7 +22186,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:22236: error: cannot find input file: $f" >&5
+           { { echo "$as_me:22189: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -22291,7 +22244,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:22294: $ac_file is unchanged" >&5
+      { echo "$as_me:22247: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
