snapshot of project "vile", label v9_8f

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,5 +1,5 @@
 #! /bin/sh
-# From configure.in Revision: 1.288 .
+# From configure.in Revision: 1.289 .
 # Guess values for system-dependent variables and create Makefiles.
 # Generated by Autoconf 2.52.20101002.
 #
@@ -26057,6 +26057,23 @@ fi
 
 fi
 
+if test -n "$loadable" ; then
+	save_LDFLAGS="$LDFLAGS"
+	LDFLAGS=`echo "x$LDFLAGS" | sed -e 's/^.//' -e 's/-Wl,--as-needed//g' -e 's/-Wl,--no-undefined//g' -e 's/  / /g'`
+	if test "x$save_LDFLAGS" != "x$LDFLAGS"
+	then
+		test -n "$verbose" && echo "	removed loader flags that interfere with loadable filters" 1>&6
+
+echo "${as_me:-configure}:26067: testing removed loader flags that interfere with loadable filters ..." 1>&5
+
+		test -n "$verbose" && echo "	flags are now $LDFLAGS" 1>&6
+
+echo "${as_me:-configure}:26071: testing flags are now $LDFLAGS ..." 1>&5
+
+		export LDFLAGS
+	fi
+fi
+
 ###	output makefile and config.h
 ac_config_files="$ac_config_files makefile filters/makefile filters/makefile.tmp:filters/makefile.2nd"
 ac_config_commands="$ac_config_commands default"
@@ -26139,7 +26156,7 @@ DEFS=-DHAVE_CONFIG_H
 : ${CONFIG_STATUS=./config.status}
 ac_clean_files_save=$ac_clean_files
 ac_clean_files="$ac_clean_files $CONFIG_STATUS"
-{ echo "$as_me:26142: creating $CONFIG_STATUS" >&5
+{ echo "$as_me:26159: creating $CONFIG_STATUS" >&5
 echo "$as_me: creating $CONFIG_STATUS" >&6;}
 cat >$CONFIG_STATUS <<_ACEOF
 #! $SHELL
@@ -26315,7 +26332,7 @@ cat >>$CONFIG_STATUS <<\EOF
     echo "$ac_cs_version"; exit 0 ;;
   --he | --h)
     # Conflict between --help and --header
-    { { echo "$as_me:26318: error: ambiguous option: $1
+    { { echo "$as_me:26335: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: ambiguous option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -26334,7 +26351,7 @@ Try \`$0 --help' for more information." >&2;}
     ac_need_defaults=false;;
 
   # This is an error.
-  -*) { { echo "$as_me:26337: error: unrecognized option: $1
+  -*) { { echo "$as_me:26354: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&5
 echo "$as_me: error: unrecognized option: $1
 Try \`$0 --help' for more information." >&2;}
@@ -26393,7 +26410,7 @@ do
   "filters/makefile.tmp" ) CONFIG_FILES="$CONFIG_FILES filters/makefile.tmp:filters/makefile.2nd" ;;
   "default" ) CONFIG_COMMANDS="$CONFIG_COMMANDS default" ;;
   "config.h" ) CONFIG_HEADERS="$CONFIG_HEADERS config.h:config_h.in" ;;
-  *) { { echo "$as_me:26396: error: invalid argument: $ac_config_target" >&5
+  *) { { echo "$as_me:26413: error: invalid argument: $ac_config_target" >&5
 echo "$as_me: error: invalid argument: $ac_config_target" >&2;}
    { (exit 1); exit 1; }; };;
   esac
@@ -26680,7 +26697,7 @@ done; }
   esac
 
   if test x"$ac_file" != x-; then
-    { echo "$as_me:26683: creating $ac_file" >&5
+    { echo "$as_me:26700: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
     rm -f "$ac_file"
   fi
@@ -26698,7 +26715,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:26701: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:26718: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -26711,7 +26728,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:26714: error: cannot find input file: $f" >&5
+           { { echo "$as_me:26731: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -26777,7 +26794,7 @@ for ac_file in : $CONFIG_HEADERS; do test "x$ac_file" = x: && continue
   * )   ac_file_in=$ac_file.in ;;
   esac
 
-  test x"$ac_file" != x- && { echo "$as_me:26780: creating $ac_file" >&5
+  test x"$ac_file" != x- && { echo "$as_me:26797: creating $ac_file" >&5
 echo "$as_me: creating $ac_file" >&6;}
 
   # First look for the input files in the build tree, otherwise in the
@@ -26788,7 +26805,7 @@ echo "$as_me: creating $ac_file" >&6;}
       -) echo $tmp/stdin ;;
       [\\/$]*)
          # Absolute (can't be DOS-style, as IFS=:)
-         test -f "$f" || { { echo "$as_me:26791: error: cannot find input file: $f" >&5
+         test -f "$f" || { { echo "$as_me:26808: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          echo $f;;
@@ -26801,7 +26818,7 @@ echo "$as_me: error: cannot find input file: $f" >&2;}
            echo $srcdir/$f
          else
            # /dev/null tree
-           { { echo "$as_me:26804: error: cannot find input file: $f" >&5
+           { { echo "$as_me:26821: error: cannot find input file: $f" >&5
 echo "$as_me: error: cannot find input file: $f" >&2;}
    { (exit 1); exit 1; }; }
          fi;;
@@ -26859,7 +26876,7 @@ cat >>$CONFIG_STATUS <<\EOF
   rm -f $tmp/in
   if test x"$ac_file" != x-; then
     if cmp -s $ac_file $tmp/config.h 2>/dev/null; then
-      { echo "$as_me:26862: $ac_file is unchanged" >&5
+      { echo "$as_me:26879: $ac_file is unchanged" >&5
 echo "$as_me: $ac_file is unchanged" >&6;}
     else
       ac_dir=`$as_expr X"$ac_file" : 'X\(.*[^/]\)//*[^/][^/]*/*$' \| \
